linters:
  disable-all: true
  enable:
    - golint
    - govet
    - gofmt
    - gocyclo
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true

severity:
  default-severity: warning
  rules:
    - linters:
        - errcheck
      severity: note
