# Don't print a new line at the start of the prompt
add_newline = false

[cmd_duration]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[package]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
symbol = ""
style = "bold blue"

[ruby]
disabled = true

[rust]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[zig]
disabled = true
