require("fw.lazy")
require("fw.options")
require("fw.globals")
require("fw.keymaps")
require("fw.autocommands")
require("fw.colorscheme")
-- require("fw.luasnip")
require("fw.cmp")
require("fw.lsp")
require("fw.vimtest")
require("fw.treesitter")
require("fw.telescope")
require("fw.lualine")
require("fw.formatter")
require("fw.ibl")
require("fw.cc")
-- require("fw.project")

-- development
-- require("testrunner")
