require("fw.packer")
require("fw.options")
require("fw.globals")
require("fw.keymaps")
require("fw.autocommands")
require("fw.colorscheme")
require("fw.luasnip")
require("fw.cmp")
require("fw.lsp")
require("fw.vimtest")
require("fw.treesitter")
require("fw.telescope")
require("fw.lualine")

-- development
-- require("testrunner")
